server:
  port : 8083
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive
    username: postgres
    password: 12345
    properties:
      schema: bookshop

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG